--- #YAML:1.0
name:               Posterous
version:            0.03
abstract:           API to posterous.com
author:
    - shelling <shelling@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Attribute::Protected:  0
    HTTP::Request:        0
    LWP::UserAgent:       0
    MIME::Base64:         0
    perl:                 5.010
    Rubyish::Attribute:   1.1
    XML::Simple:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
